<%@ Page Language="C#" AutoEventWireup="true" CodeBehind="MostrarMedico.aspx.cs" Inherits="TPINT_GRUPO_2_PR3.Vistas.MostrarMedico" %>

<!DOCTYPE html>

<html xmlns="http://www.w3.org/1999/xhtml">

<head runat="server">
<meta http-equiv="Content-Type" content="text/html; charset=utf-8"/>
<title>Listado de Médicos</title>
<style>

body{
    background:#277343;
    font-family:Arial, Helvetica, sans-serif;
    margin:0;
    padding:30px;
}

#contenedor{
    width:95%;
    max-width:1200px;
    margin:40px auto;
    background:white;
    padding:25px;
    border-radius:10px;
    box-shadow:0 0 15px rgba(0,0,0,.25);
}

.grid{
    width:100%;
    border-collapse:collapse;
    background:white;
}

.grid th{
    background:#277343;
    color:white;
    padding:10px;
    text-align:center;
}

.grid td{
    padding:8px;
    border:1px solid #d9d9d9;
    text-align:center;
}

.grid tr:nth-child(even){
    background:#f4f4f4;
}

.grid tr:hover{
    background:#dff0e2;
}

.titulo{
    text-align:center;
    color:#277343;
}

.mensaje{
    text-align:center;
    margin-bottom:15px;
}

</style>
</head>
<body>
<form id="form1" runat="server">
    <div id="contenedor">
        <div style="text-align:center;">
            <asp:Label ID="lblNombreUsuario" runat="server">| Nombre Usuario |</asp:Label>
        </div>
        <h2 class="titulo">
            Médicos Registrados
        </h2>
        <div class="mensaje">
            <asp:Label ID="lblMensaje" runat="server" ForeColor="Red"> </asp:Label>
        </div>
        <div style="overflow-x:auto;">
            <asp:GridView ID="gvMedicos" runat="server" CssClass="grid" AutoGenerateColumns="True" AutoGenerateDeleteButton="True" DataKeyNames="id_med" OnRowDeleting="gvMedicos_RowDeleting" AllowPaging="True" OnPageIndexChanging="gvMedicos_PageIndexChanging">
            </asp:GridView>
        </div>
        <br />
        <div style="text-align:center;">
            <asp:Button ID="btnVolver" runat="server" Text="Volver" OnClick="btnVolver_Click" />
        </div>
    </div>
</form>
</body>
</html>